name: Generate Package Lock and Send Emails

on:
  workflow_dispatch: # Gatilho manual

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - uses: actions/checkout@v2

      # 2. Configuração do Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      # 3. Instalação de dependências, incluindo dotenv e nodemailer
      - name: Install Dependencies
        run: |
          npm install dotenv nodemailer
          npm install lucide-react@latest
          npm install --legacy-peer-deps
          npm install --save-dev typescript @types/react @types/node
     
      # 3.1. Corrige as dependências
      - name: Fix Dependencies
        run: npm audit fix --force

      # 4. Configura e executa o script de envio de e-mails
      - name: Run Email Script
        run: node sendEmailsSMTP.js
        env:
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_EMAIL_DESTINATION: ${{ secrets.SMTP_EMAIL_DESTINATION }}

      # 5. Commit e push do package-lock.json
      - name: Commit package-lock.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add package-lock.json
          git commit -m "Add package-lock.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
